version: "3"
services:
    web:
        build: .
        ports:
            - "5001:5001"
        volumes:
            - .:/app
        environment:
          - FLASK_APP=app.py
          - FLASK_DEBUG=0
          - PYTHONUNBUFFERED=True
        command: gunicorn  -b 0.0.0.0:5001 app:app --reload
